[profile.default]
src = 'contracts'
test = 'test'
out = 'artifacts/contracts'
libs = ['lib']
no_match_path = "contracts/*"
solc_version = '0.5.16'
optimizer = true
optimizer_runs = 20_000
eth_rpc_url = "https://api.harmony.one"

[profile.test]
fork_block_number = 61451319
